### PR TITLE
update README file

### PR DESCRIPTION
**Pull request by mingohan**
add  README file
加入環境變數設定說明

### CODE REVIEW

**Comment by yulingyou** [comment]
OK

**Review by yulingyou — APPROVED** [review]

**Comment by JacoChu** [comment]
Ok

**Comment by linyunxi** [comment]
ok

**Review by linyunxi — APPROVED** [review]

**Review by JacoChu — APPROVED** [review]

**Review by erichg007 — APPROVED** [review]

**Review by JacoChu — APPROVED** [review]

**Review by JacoChu — APPROVED** [review]

**Review by JacoChu — APPROVED** [review]

**Review by JacoChu — APPROVED** [review]

**Review by erichg007 — APPROVED** [review]
good job

**Review by erichg007 — APPROVED** [review]
good job

**Pull request merged**
